### ISSUE TITLE
[BUG] NA handling in classification metrics

### ISSUE THREAD

**Issue by EmilHvitfeldt** [serkor1/SLmetrics#8]
## issue

Great job on the package! it has good performance.

when looking at the package, i noticed that it isn't clearly documented behavior with regards to how missing values are handled. From the limited testing, i see that for regression metrics you get an `NA` if there `NA`s in the input, but they are ignored in classification settings.

I wasn't able to find if this is expected, according to the documentation or not.

## reprex

``` r
library(SLmetrics)
#> Loading {SLmetrics} v0.1.0

fct1 <- factor(c("yes", "no"))
fct2 <- factor(c("yes", "no"))

accuracy(fct1, fct2)
#> [1] 1

fct1[1] <- NA

accuracy(fct1, fct2)
#> [1] 0.5
```

**Comment by serkor1** [comment]
Hi @EmilHvitfeldt,

Thank you for taking the time to post this issue. And thank you for your words, that means a lot coming from you. On an honest side-note I would have expected the R session to crash in the presence of `NA` as it does for the following example,

```r
SLmetrics::specificity(
  factor(c("no", "no", "yes")),
  factor(c("no", "no", NA)),
)
```

In the case of pair-wise metrics like `accuracy()` and `baccuracy()`, I did not consider `NA`-values from the get-go. This is also why it is not documented anywhere. But I think adding a `na.rm`-argument to the functions will do the trick such that the behavior is predictable, and well-documented.
